baseURL = 'https://psilva.org/'
languageCode = 'en-us'
title = 'psilva.org'
theme = 'kong-htop'
paginate = 10
pluralizelisttitles = false

[Author]
name = "Gabriel Pereira da Silva"

[params]
    title = "psilva.org"
    brand = "psilva.org"
    author_name = "Gabriel Pereira da Silva"
    description = "Thoughts on technology, creativity, and continuous learning."
    brand_image = "/images/avatar.png"
    dark_mode = true
    content_bg_color_dark = "#090910"
    sidebar_bg_color = "#141420"
    mainSections = ["posts"]
    twitter_url = "https://x.com/gabes_tint"
    github_url = "https://github.com/gabepsilva"
    linkedin_url = "https://linkedin.com/in/gabrielpe"

    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Categories", URL = "/categories/", HasChildren = false},
        {Name = "Tags", URL = "/tags/", HasChildren = false},
    ]

    rss_icon = true
    rss_section = "posts"

[taxonomies]
    series = 'series'
    tags = 'tags'
    categories = 'categories'

[outputs]
    home = ["HTML", "RSS", "JSON"]
    section = ["HTML"]
    page = ["HTML"]

[outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
